import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="learning roadmap ability map skill tree knowledge graph prerequisite learning order learning phase beginner intermediate advanced job goal frontend road backend road full-stack AI road data road cloud native road security road embedded road CS foundation road postgraduate exam road job hunting road portfolio road course combination module dependency phase goal ability assessment learning milestone project acceptance error review knowledge gap time budget learning rhythm route adjustment path recommendation module navigation roadmap design career path skill matrix competency model learning path personalized learning adaptive learning self-directed learning outcome-based education competency-based education micro-credential digital badge portfolio assessment project-based learning inquiry-based learning problem-based learning experiential learning flipped classroom blended learning MOOC SPOC open educational resource OER learning analytics data-driven learning personalized recommendation intelligent tutoring system adaptive learning path knowledge tracing skill acquisition deliberate practice deliberate learning mastery learning self-paced learning scaffold learning zone of proximal development spiral curriculum backward design constructive alignment learning outcome program outcome graduate attribute curriculum mapping curriculum design instructional design learning design learning experience design LX design educational technology edtech learning engineering";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"rm-tag-"+String(i+1).padStart(3,"0"),name:n,category:"Roadmap",description:"Road标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"rm-course-01",order:1,slug:"RM入门",title:"学习路线规划入门",description:"路线价值、能力地图、学习方法。",estimatedHours:4,diff:"easy"},
  {id:"rm-course-02",order:2,slug:"SkillTree",title:"能力地图、知识树与技能图谱",description:"技能树构建、知识体系、图谱工具。",estimatedHours:8,diff:"easy"},
  {id:"rm-course-03",order:3,slug:"编程入门",title:"编程入门路线规划",description:"零基础路线、语言选择、实践路径。",estimatedHours:8,diff:"easy"},
  {id:"rm-course-04",order:4,slug:"前端路线",title:"前端开发路线规划",description:"HTML/CSS/JS到框架、全链路。",estimatedHours:8,diff:"medium"},
  {id:"rm-course-05",order:5,slug:"后端路线",title:"后端开发路线规划",description:"Java/Go/Python后端技术栈路线。",estimatedHours:8,diff:"medium"},
  {id:"rm-course-06",order:6,slug:"数据路线",title:"数据分析与数据工程路线规划",description:"数据分析/BI/数据工程/大数据路线。",estimatedHours:8,diff:"medium"},
  {id:"rm-course-07",order:7,slug:"AI路线",title:"AI、大模型与智能应用路线规划",description:"ML/DL/LLM/AI应用开发路线。",estimatedHours:10,diff:"hard"},
  {id:"rm-course-08",order:8,slug:"CS基础",title:"计算机专业基础路线规划",description:"OS/网络/数据库/数据结构/组成路线。",estimatedHours:8,diff:"medium"},
  {id:"rm-course-09",order:9,slug:"DevOps路线",title:"DevOps、云原生与部署路线规划",description:"Docker/K8s/CI/CD/云服务路线。",estimatedHours:8,diff:"hard"},
  {id:"rm-course-10",order:10,slug:"安全嵌入式",title:"安全、系统、嵌入式与底层路线规划",description:"安全/嵌入式/系统编程路线。",estimatedHours:8,diff:"hard"},
  {id:"rm-course-11",order:11,slug:"求职路线",title:"求职、作品集与面试路线规划",description:"简历/面试/作品集/求职节奏路线。",estimatedHours:8,diff:"medium"},
  {id:"rm-course-12",order:12,slug:"课程组合",title:"课程组合、前置知识与学习顺序",description:"模块依赖、前置知识、学习序列。",estimatedHours:10,diff:"hard"},
  {id:"rm-course-13",order:13,slug:"评估调整",title:"阶段验收、能力评估与路线调整",description:"验收标准、能力测评、路线修正。",estimatedHours:8,diff:"hard"},
  {id:"rm-course-14",order:14,slug:"OG路线",title:"OpenSkill Galaxy综合路线设计",description:"60模块综合路线、个性化路径。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["能制定学习路线","能规划能力地图","会选择模块","能评估进度"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"rm-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["Roadmap"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"RM课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["学习路线","路径规划"],["能力地图","技能体系"],["技能树","知识结构"],["前置知识","学习前提"],["前端路线","Web开发"],["后端路线","服务端"],["AI路线","人工智能"],["数据路线","数据分析"],["DevOps","运维开发"],["安全路线","安全工程"],["嵌入式","系统编程"],["求职路线","就业路径"],["课程组合","模块搭配"],["阶段验收","进度检查"],["路线调整","优化修正"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"rm-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"Roadmap",tags:["Roadmap"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"rm-kp-"+String(k.length+1).padStart(4,"0"),name:"Road概念"+(k.length+1),description:"Road概念",category:"Roadmap",tags:["Roadmap"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["RM入门","SkillTree","编程入门","前端路线","后端路线","数据路线","AI路线","CS基础","DevOps路线","安全嵌入式","求职路线","课程组合","评估调整","OG路线"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"学习路线核心？",["明确目标和路径","只看书","只做题","只听课"],"A","easy"],[1,"技能树作用？",["可视化知识体系","替代学习","代替考试","替代项目"],"A","easy"],[2,"编程入门推荐？",["从基础语法开始","直接学框架","只看视频","不做练习"],"A","easy"],[3,"前端基础三件套？",["HTML/CSS/JS","Java/C++/Python","Node/React/Vue","Git/Docker/Mongo"],"A","medium"],[4,"Java后端核心？",["Java/Spring/数据库","HTML/CSS","React/Vue","Git"],"A","medium"],[5,"AI学习前置？",["数学和编程基础","美术","音乐","外语"],"A","medium"],[6,"模块前置知识影响？",["学习顺序和效果","模块数量","模块大小","模块颜色"],"A","hard"],[7,"阶段验收方式？",["项目/测试/复盘","只看书","只听课","只记笔记"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"rm-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:650},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:850},{type:"case_analysis",min:1500}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="rm-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于路线"+ch+"以下正确的是？",""+ch+"的核心是？","以下哪个不是"+ch+"的内容？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="路线"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是学习路线规划的重要概念。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="路线"+ch+"中____是关键。";o=[{label:"A",text:"____"}];a="关键";}
    else if(it.type==="short_answer"){s="简述"+ch+"在学习路线规划中的作用。";o=[{label:"A",text:"简答"}];a=ch+"很重要。";}
    else if(it.type==="case_analysis"){s="路线"+ch+"案例：设计方案。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"rm-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["零基础学编程","C到嵌入式","Python到数据分析","Python到AI","前端入门到React","Java后端","Go后端","全栈","数据工程","AI产品经理","RAG应用","云原生","安全入门","考研基础","求职冲刺","作品集","60模块总路线"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"rm-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握路线规划",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"背景",description:"分析"},{order:2,title:"方案",description:"设计"},{order:3,title:"执行",description:"实施"},{order:4,title:"评估",description:"检查"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"RM路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"rm-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["学习路线","能力地图","技能树","前置知识","前端路线","后端路线","AI路线","数据路线","DevOps","安全","嵌入式","求职","课程组合","验收","调整"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["Road概念"+i,"Road概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"rm-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"Roadmap",tags:["Roadmap"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["路线问题"+(i+1)+"?","路线问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"rm-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"Roadmap",tags:["Roadmap"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["Roadmap"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["Roadmap"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["Roadmap"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["Roadmap"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["Roadmap"]});});return e;}
async function main(){
  console.log("Gen Roadmap...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-roadmap-navigator",slug:"module-roadmap-navigator",title:"学习路线规划与能力地图",subtitle:"面向全平台学习者",description:"面向全平台学习者的学习路线能力地图知识树模块依赖岗位方向阶段目标项目作品能力评估与个性化学习路径设计训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["学习路线","能力地图","技能树","路线规划","岗位方向","模块导航","学习路径","能力评估"],estimatedHours:140,difficulty:"beginner",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F9F0}",repoUrl:"https://github.com/openskill-galaxy/module-roadmap-navigator",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
